use_frameworks!

platform :ios, '10.0'

target 'MediaEditorManager_Example' do
  pod 'MediaEditorManager', :path => '../'

  target 'MediaEditorManager_Tests' do
    inherit! :search_paths

    
  end
end
